[meta]
name = "Just Like Wordle"
author = "R1DF"
date = "01.01.2022"
description = "Would you like the standard Wordle experience instead?"

[data]
# MISC.
bg = "#9E9041"
text_fill = "GREEN"
text_invalid = "RED"
line_fill = "BLACK"

# BUTTON
button_fill = "#C8B653"
button_highlight = "#E0D075"

# SELECTOR
selector_fill = "#C8B653"
selector_highlight = "#FFE873"

# SCALE
scale_fill = "#C8B653"
scale_highlight = "#FFE873"
scale_cursor = "WHITE"
scale_border = "RED"

# LOADING BAR - This widget is unused, so themes do not necessarily have to need this installed.
loading_bar_increase_fill = "GREEN"

# SELECTOR LIST / ELEMENT
selector_list_fill = "#9E9041"
selector_element_fill = "#9E9041"
selector_element_highlight = "#E0D075"
selector_element_selected = "YELLOW"

# GRID
grid_square_fill = "#4A4D4F"
grid_square_correct = "#6CA965"
grid_square_mismatched = "#C8B653"
grid_square_incorrect = "#808080"
grid_square_border = "BLACK"
grid_square_text_fill = "BLACK"

