[window]
resolutions = [
    [500, 600],
    [800, 900],
    [100, 200]
]
default_resolution_index = 0

[text]
font_family = "Franklin Gothic Medium"
text_size_huge = 50
text_size_big = 30
text_size_mid = 20
text_size_small = 15